"""
GIAS-modelled special school dataset for England.
Each school includes: SEN provision codes, capacity, vacancies,
Ofsted rating, specialist facilities, and geographic coordinates.

SEN codes (official DfE taxonomy):
  ASD  - Autism Spectrum Disorder
  SEMH - Social, Emotional and Mental Health
  SLCN - Speech, Language and Communication Needs
  MLD  - Moderate Learning Difficulty
  SLD  - Severe Learning Difficulty
  PMLD - Profound and Multiple Learning Difficulty
  SpLD - Specific Learning Difficulty (Dyslexia, Dyspraxia)
  HI   - Hearing Impairment
  VI   - Visual Impairment
  MSI  - Multi-Sensory Impairment
  PD   - Physical Disability
  OTH  - Other
"""

SCHOOLS = [
    {
        "id": "S001",
        "name": "Oakfield Academy",
        "address": "12 Oak Lane, Manchester, M14 4PQ",
        "lat": 53.4437, "lng": -2.2145,
        "sen_provision": ["ASD", "SEMH", "SLCN"],
        "capacity": 120,
        "vacancies": 8,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["sensory_room", "speech_therapy", "aba_unit"],
        "age_range": "5-19",
        "region": "North West"
    },
    {
        "id": "S002",
        "name": "Sunfield School",
        "address": "45 Elm Road, Birmingham, B29 5DP",
        "lat": 52.4478, "lng": -1.9546,
        "sen_provision": ["ASD", "SLD", "PMLD"],
        "capacity": 80,
        "vacancies": 3,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Independent Special School",
        "facilities": ["hydrotherapy", "sensory_room", "physiotherapy", "occupational_therapy"],
        "age_range": "5-19",
        "region": "West Midlands"
    },
    {
        "id": "S003",
        "name": "Heathfield Special School",
        "address": "78 Heath Drive, Leeds, LS6 3BN",
        "lat": 53.8192, "lng": -1.5640,
        "sen_provision": ["PD", "PMLD", "SLD", "HI"],
        "capacity": 95,
        "vacancies": 12,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["physiotherapy", "hydrotherapy", "hearing_support", "occupational_therapy", "wheelchair_access"],
        "age_range": "2-19",
        "region": "Yorkshire"
    },
    {
        "id": "S004",
        "name": "The Bridge School",
        "address": "23 Bridge Street, London, N7 8QP",
        "lat": 51.5516, "lng": -0.1126,
        "sen_provision": ["ASD", "SEMH", "MLD", "SLCN"],
        "capacity": 150,
        "vacancies": 5,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Academy Special School",
        "facilities": ["sensory_room", "speech_therapy", "counselling", "life_skills_kitchen"],
        "age_range": "4-16",
        "region": "London"
    },
    {
        "id": "S005",
        "name": "Meadowbrook College",
        "address": "56 Meadow Lane, Bristol, BS4 3ET",
        "lat": 51.4369, "lng": -2.5679,
        "sen_provision": ["SEMH", "MLD", "SpLD"],
        "capacity": 60,
        "vacancies": 15,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["counselling", "art_therapy", "vocational_workshop"],
        "age_range": "11-19",
        "region": "South West"
    },
    {
        "id": "S006",
        "name": "Lindsworth School",
        "address": "99 King's Road, Birmingham, B30 3QU",
        "lat": 52.4140, "lng": -1.8820,
        "sen_provision": ["SEMH", "ASD", "MLD"],
        "capacity": 85,
        "vacancies": 0,
        "ofsted": "Requires Improvement",
        "ofsted_score": 2,
        "school_type": "Community Special School",
        "facilities": ["counselling", "sports_therapy"],
        "age_range": "5-16",
        "region": "West Midlands"
    },
    {
        "id": "S007",
        "name": "Blanche Nevile School",
        "address": "40 Lordship Lane, London, N17 6RT",
        "lat": 51.5956, "lng": -0.0697,
        "sen_provision": ["HI", "MSI", "SLCN"],
        "capacity": 70,
        "vacancies": 7,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["hearing_support", "bsl_unit", "radio_aid_systems", "speech_therapy"],
        "age_range": "3-19",
        "region": "London"
    },
    {
        "id": "S008",
        "name": "RNIB Sunshine House",
        "address": "6 Albion Road, Northwood, HA6 2AJ",
        "lat": 51.6055, "lng": -0.4178,
        "sen_provision": ["VI", "MSI", "PMLD"],
        "capacity": 55,
        "vacancies": 4,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Independent Special School",
        "facilities": ["braille_unit", "low_vision_aids", "orientation_mobility", "hydrotherapy"],
        "age_range": "2-19",
        "region": "London"
    },
    {
        "id": "S009",
        "name": "Piper Hill High School",
        "address": "200 Yew Tree Lane, Manchester, M23 0FF",
        "lat": 53.3814, "lng": -2.2728,
        "sen_provision": ["SLD", "PMLD", "ASD", "PD"],
        "capacity": 100,
        "vacancies": 9,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["hydrotherapy", "sensory_room", "physiotherapy", "occupational_therapy", "wheelchair_access"],
        "age_range": "11-19",
        "region": "North West"
    },
    {
        "id": "S010",
        "name": "Springfield School Sheffield",
        "address": "Stannington View Road, Sheffield, S10 1GS",
        "lat": 53.3835, "lng": -1.5119,
        "sen_provision": ["MLD", "SLCN", "SpLD", "SEMH"],
        "capacity": 110,
        "vacancies": 20,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["speech_therapy", "reading_recovery", "counselling"],
        "age_range": "5-16",
        "region": "Yorkshire"
    },
    {
        "id": "S011",
        "name": "Horizon School",
        "address": "14 Horizon Way, Nottingham, NG5 6JR",
        "lat": 52.9779, "lng": -1.1335,
        "sen_provision": ["ASD", "SLCN", "SEMH"],
        "capacity": 90,
        "vacancies": 11,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Academy Special School",
        "facilities": ["sensory_room", "aba_unit", "speech_therapy", "counselling"],
        "age_range": "4-19",
        "region": "East Midlands"
    },
    {
        "id": "S012",
        "name": "Exhall Grange School",
        "address": "Church Lane, Exhall, Coventry, CV7 9HP",
        "lat": 52.4516, "lng": -1.5100,
        "sen_provision": ["PD", "HI", "VI", "MLD", "SLD"],
        "capacity": 130,
        "vacancies": 6,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Academy Special School",
        "facilities": ["physiotherapy", "hydrotherapy", "hearing_support", "low_vision_aids", "wheelchair_access", "occupational_therapy"],
        "age_range": "2-19",
        "region": "West Midlands"
    },
    {
        "id": "S013",
        "name": "St Elizabeth's Centre",
        "address": "South End, Much Hadham, Hertfordshire, SG10 6EW",
        "lat": 51.8636, "lng": 0.0602,
        "sen_provision": ["PMLD", "SLD", "ASD", "PD"],
        "capacity": 65,
        "vacancies": 2,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Independent Special School",
        "facilities": ["hydrotherapy", "physiotherapy", "sensory_room", "occupational_therapy", "residential"],
        "age_range": "5-19",
        "region": "East of England"
    },
    {
        "id": "S014",
        "name": "Barrs Court School",
        "address": "Barrs Court Road, Hereford, HR1 1EQ",
        "lat": 52.0563, "lng": -2.6932,
        "sen_provision": ["ASD", "SLD", "SEMH"],
        "capacity": 75,
        "vacancies": 14,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["sensory_room", "counselling", "vocational_workshop"],
        "age_range": "5-19",
        "region": "West Midlands"
    },
    {
        "id": "S015",
        "name": "Coppice School",
        "address": "Coppice Road, Arnold, Nottingham, NG5 7GR",
        "lat": 52.9998, "lng": -1.1094,
        "sen_provision": ["MLD", "SEMH", "SpLD", "SLCN"],
        "capacity": 105,
        "vacancies": 18,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["counselling", "speech_therapy", "reading_recovery"],
        "age_range": "5-16",
        "region": "East Midlands"
    },
    {
        "id": "S016",
        "name": "The Severndale Academy",
        "address": "Sundorne Road, Shrewsbury, SY1 4RQ",
        "lat": 52.7333, "lng": -2.7361,
        "sen_provision": ["ASD", "SLD", "PMLD", "SLCN", "PD"],
        "capacity": 200,
        "vacancies": 22,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Academy Special School",
        "facilities": ["hydrotherapy", "sensory_room", "physiotherapy", "speech_therapy", "occupational_therapy", "wheelchair_access"],
        "age_range": "2-19",
        "region": "West Midlands"
    },
    {
        "id": "S017",
        "name": "Thornbeck College",
        "address": "Thornholme Road, Sunderland, SR2 7NA",
        "lat": 54.8935, "lng": -1.3720,
        "sen_provision": ["PMLD", "SLD", "ASD"],
        "capacity": 50,
        "vacancies": 5,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["sensory_room", "hydrotherapy", "physiotherapy"],
        "age_range": "16-25",
        "region": "North East"
    },
    {
        "id": "S018",
        "name": "Wargrave House School",
        "address": "449 Wargrave Road, Newton-le-Willows, WA12 8RS",
        "lat": 53.4532, "lng": -2.6191,
        "sen_provision": ["ASD", "SEMH"],
        "capacity": 65,
        "vacancies": 3,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Independent Special School",
        "facilities": ["aba_unit", "sensory_room", "speech_therapy", "counselling"],
        "age_range": "5-19",
        "region": "North West"
    },
    {
        "id": "S019",
        "name": "Chailey Heritage School",
        "address": "Haywards Heath Road, Chailey, East Sussex, BN8 4EF",
        "lat": 50.9695, "lng": 0.0261,
        "sen_provision": ["PD", "PMLD", "SLD", "VI"],
        "capacity": 120,
        "vacancies": 8,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Independent Special School",
        "facilities": ["physiotherapy", "hydrotherapy", "wheelchair_access", "low_vision_aids", "occupational_therapy", "residential"],
        "age_range": "3-19",
        "region": "South East"
    },
    {
        "id": "S020",
        "name": "Portland College",
        "address": "Nottingham Road, Mansfield, NG18 4TJ",
        "lat": 53.1417, "lng": -1.1947,
        "sen_provision": ["PD", "ASD", "MLD", "SLD"],
        "capacity": 80,
        "vacancies": 10,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Independent Special School",
        "facilities": ["physiotherapy", "occupational_therapy", "wheelchair_access", "vocational_workshop", "residential"],
        "age_range": "16-25",
        "region": "East Midlands"
    },
    {
        "id": "S021",
        "name": "North West London School for the Deaf",
        "address": "Wyvil Road, London, SW8 2TH",
        "lat": 51.4787, "lng": -0.1256,
        "sen_provision": ["HI", "MSI", "SLCN"],
        "capacity": 60,
        "vacancies": 6,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["hearing_support", "bsl_unit", "radio_aid_systems", "speech_therapy"],
        "age_range": "3-16",
        "region": "London"
    },
    {
        "id": "S022",
        "name": "Icknield School",
        "address": "Ridgeway Road, Letchworth, Hertfordshire, SG6 4QA",
        "lat": 51.9761, "lng": -0.2337,
        "sen_provision": ["MLD", "SpLD", "SLCN", "ASD"],
        "capacity": 90,
        "vacancies": 16,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["reading_recovery", "speech_therapy", "sensory_room"],
        "age_range": "5-16",
        "region": "East of England"
    },
    {
        "id": "S023",
        "name": "Rodney House School",
        "address": "Auchmuty Road, Kirkcaldy, Nottingham, NG2 3AA",
        "lat": 52.9374, "lng": -1.1474,
        "sen_provision": ["SEMH", "MLD", "ASD"],
        "capacity": 55,
        "vacancies": 7,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["counselling", "art_therapy"],
        "age_range": "5-16",
        "region": "East Midlands"
    },
    {
        "id": "S024",
        "name": "Penn Fields School",
        "address": "Bhylls Acre, Wolverhampton, WV3 8DA",
        "lat": 52.5716, "lng": -2.1552,
        "sen_provision": ["SLD", "PMLD", "ASD", "PD", "SLCN"],
        "capacity": 115,
        "vacancies": 13,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["hydrotherapy", "sensory_room", "physiotherapy", "wheelchair_access", "speech_therapy"],
        "age_range": "2-19",
        "region": "West Midlands"
    },
    {
        "id": "S025",
        "name": "Grafham Grange School",
        "address": "Bramley, Guildford, Surrey, GU5 0LH",
        "lat": 51.1846, "lng": -0.5248,
        "sen_provision": ["SEMH", "SpLD", "MLD"],
        "capacity": 45,
        "vacancies": 9,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Independent Special School",
        "facilities": ["counselling", "equine_therapy", "vocational_workshop"],
        "age_range": "11-16",
        "region": "South East"
    },
    {
        "id": "S026",
        "name": "Meldreth Manor School",
        "address": "High Street, Meldreth, Royston, SG8 6LG",
        "lat": 52.0822, "lng": 0.0178,
        "sen_provision": ["PD", "SLD", "PMLD", "MSI"],
        "capacity": 70,
        "vacancies": 4,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Independent Special School",
        "facilities": ["physiotherapy", "hydrotherapy", "sensory_room", "low_vision_aids", "wheelchair_access", "occupational_therapy"],
        "age_range": "2-19",
        "region": "East of England"
    },
    {
        "id": "S027",
        "name": "Longwill School",
        "address": "Bell Hill, Northfield, Birmingham, B31 1LD",
        "lat": 52.4064, "lng": -1.9643,
        "sen_provision": ["HI", "SLCN", "MLD"],
        "capacity": 80,
        "vacancies": 11,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["hearing_support", "bsl_unit", "speech_therapy"],
        "age_range": "2-16",
        "region": "West Midlands"
    },
    {
        "id": "S028",
        "name": "Priory School",
        "address": "Pampisford Road, South Croydon, CR2 6RA",
        "lat": 51.3568, "lng": -0.0775,
        "sen_provision": ["ASD", "SLD", "SLCN"],
        "capacity": 100,
        "vacancies": 0,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["sensory_room", "speech_therapy", "aba_unit"],
        "age_range": "4-19",
        "region": "London"
    },
    {
        "id": "S029",
        "name": "Ramsden Hall Academy",
        "address": "Heath Road, Billericay, Essex, CM11 1HN",
        "lat": 51.6168, "lng": 0.4250,
        "sen_provision": ["SEMH", "MLD", "SpLD"],
        "capacity": 90,
        "vacancies": 20,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Academy Special School",
        "facilities": ["counselling", "vocational_workshop", "sports_therapy"],
        "age_range": "11-16",
        "region": "East of England"
    },
    {
        "id": "S030",
        "name": "Beaumont College",
        "address": "Slyne Road, Lancaster, LA2 6AP",
        "lat": 54.0660, "lng": -2.7690,
        "sen_provision": ["PD", "SLD", "PMLD", "ASD"],
        "capacity": 65,
        "vacancies": 7,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Independent Special School",
        "facilities": ["physiotherapy", "hydrotherapy", "wheelchair_access", "occupational_therapy", "residential"],
        "age_range": "16-25",
        "region": "North West"
    },
    {
        "id": "S031",
        "name": "Rectory Paddock School",
        "address": "Rectory Lane, Orpington, BR6 9SL",
        "lat": 51.3884, "lng": 0.0884,
        "sen_provision": ["SLD", "PMLD", "ASD", "MLD"],
        "capacity": 85,
        "vacancies": 6,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["sensory_room", "hydrotherapy", "physiotherapy"],
        "age_range": "2-19",
        "region": "London"
    },
    {
        "id": "S032",
        "name": "Eden Grove School",
        "address": "Holme, Carnforth, Lancashire, LA6 1RJ",
        "lat": 54.2134, "lng": -2.5621,
        "sen_provision": ["SEMH", "ASD", "MLD"],
        "capacity": 48,
        "vacancies": 5,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Independent Special School",
        "facilities": ["counselling", "equine_therapy", "outdoor_learning"],
        "age_range": "5-17",
        "region": "North West"
    },
    {
        "id": "S033",
        "name": "Rutherford School",
        "address": "Melville Avenue, South Croydon, CR2 7HZ",
        "lat": 51.3476, "lng": -0.0891,
        "sen_provision": ["PD", "SLD", "HI", "VI"],
        "capacity": 100,
        "vacancies": 9,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["physiotherapy", "wheelchair_access", "hearing_support", "low_vision_aids", "occupational_therapy"],
        "age_range": "2-19",
        "region": "London"
    },
    {
        "id": "S034",
        "name": "Sketchley Hill School",
        "address": "Sketchley Hill, Burbage, Hinckley, LE10 3HX",
        "lat": 52.5108, "lng": -1.3598,
        "sen_provision": ["PMLD", "SLD", "PD"],
        "capacity": 55,
        "vacancies": 3,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["hydrotherapy", "physiotherapy", "sensory_room", "wheelchair_access"],
        "age_range": "2-19",
        "region": "East Midlands"
    },
    {
        "id": "S035",
        "name": "The Cedar School",
        "address": "Wilton Road, Southampton, SO15 5DE",
        "lat": 50.9001, "lng": -1.4255,
        "sen_provision": ["ASD", "SEMH", "SLCN", "MLD"],
        "capacity": 110,
        "vacancies": 15,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["sensory_room", "speech_therapy", "counselling"],
        "age_range": "4-19",
        "region": "South East"
    },
    {
        "id": "S036",
        "name": "St John's School",
        "address": "Grove Road, Brighton, BN3 1AE",
        "lat": 50.8280, "lng": -0.1742,
        "sen_provision": ["SpLD", "MLD", "SLCN", "ASD"],
        "capacity": 100,
        "vacancies": 12,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Independent Special School",
        "facilities": ["reading_recovery", "speech_therapy", "occupational_therapy"],
        "age_range": "7-19",
        "region": "South East"
    },
    {
        "id": "S037",
        "name": "Sheiling School",
        "address": "Horton Road, Ringwood, Hampshire, BH24 3QG",
        "lat": 50.8358, "lng": -1.7761,
        "sen_provision": ["ASD", "SLD", "SEMH"],
        "capacity": 55,
        "vacancies": 8,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Independent Special School",
        "facilities": ["sensory_room", "art_therapy", "equine_therapy", "residential"],
        "age_range": "6-19",
        "region": "South East"
    },
    {
        "id": "S038",
        "name": "Henshaws College",
        "address": "Bogs Lane, Harrogate, HG1 4ED",
        "lat": 54.0075, "lng": -1.5194,
        "sen_provision": ["VI", "MSI", "PD", "MLD"],
        "capacity": 75,
        "vacancies": 10,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Independent Special School",
        "facilities": ["braille_unit", "low_vision_aids", "orientation_mobility", "physiotherapy", "residential"],
        "age_range": "16-25",
        "region": "Yorkshire"
    },
    {
        "id": "S039",
        "name": "East Midlands School for the Deaf",
        "address": "Stanton Road, Derby, DE72 3QE",
        "lat": 52.8571, "lng": -1.3788,
        "sen_provision": ["HI", "MSI", "SLCN", "MLD"],
        "capacity": 60,
        "vacancies": 9,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["hearing_support", "bsl_unit", "radio_aid_systems", "speech_therapy"],
        "age_range": "3-19",
        "region": "East Midlands"
    },
    {
        "id": "S040",
        "name": "Turney School",
        "address": "Turney Road, London, SE21 7JB",
        "lat": 51.4434, "lng": -0.0856,
        "sen_provision": ["ASD", "SLD", "MLD", "SLCN", "SEMH"],
        "capacity": 140,
        "vacancies": 7,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["sensory_room", "speech_therapy", "aba_unit", "counselling", "life_skills_kitchen"],
        "age_range": "4-19",
        "region": "London"
    },
    {
        "id": "S041",
        "name": "Moorland View School",
        "address": "Station Road, Mirfield, West Yorkshire, WF14 9QD",
        "lat": 53.6746, "lng": -1.6857,
        "sen_provision": ["SEMH", "ASD", "MLD", "SLCN"],
        "capacity": 70,
        "vacancies": 4,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Academy Special School",
        "facilities": ["counselling", "sensory_room", "speech_therapy"],
        "age_range": "5-16",
        "region": "Yorkshire"
    },
    {
        "id": "S042",
        "name": "Shaftesbury School",
        "address": "Rush Common, Abingdon, Oxfordshire, OX14 4PD",
        "lat": 51.6870, "lng": -1.2943,
        "sen_provision": ["PD", "SLD", "ASD", "PMLD"],
        "capacity": 95,
        "vacancies": 14,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Academy Special School",
        "facilities": ["physiotherapy", "wheelchair_access", "hydrotherapy", "occupational_therapy"],
        "age_range": "2-19",
        "region": "South East"
    },
    {
        "id": "S043",
        "name": "Ruskin Mill College",
        "address": "Old Bristol Road, Nailsworth, GL6 0LA",
        "lat": 51.7005, "lng": -2.2244,
        "sen_provision": ["ASD", "SEMH", "SpLD", "MLD"],
        "capacity": 50,
        "vacancies": 6,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Independent Special School",
        "facilities": ["art_therapy", "vocational_workshop", "equine_therapy", "outdoor_learning"],
        "age_range": "16-25",
        "region": "South West"
    },
    {
        "id": "S044",
        "name": "George Hastwell School",
        "address": "Walney Road, Barrow-in-Furness, LA14 3HJ",
        "lat": 54.1082, "lng": -3.2366,
        "sen_provision": ["SLD", "PMLD", "ASD", "PD"],
        "capacity": 80,
        "vacancies": 11,
        "ofsted": "Good",
        "ofsted_score": 3,
        "school_type": "Community Special School",
        "facilities": ["hydrotherapy", "sensory_room", "physiotherapy", "wheelchair_access"],
        "age_range": "2-19",
        "region": "North West"
    },
    {
        "id": "S045",
        "name": "Brays School",
        "address": "Brays Road, Sheldon, Birmingham, B26 1NS",
        "lat": 52.4607, "lng": -1.8031,
        "sen_provision": ["PMLD", "SLD", "ASD", "PD", "HI"],
        "capacity": 105,
        "vacancies": 5,
        "ofsted": "Outstanding",
        "ofsted_score": 4,
        "school_type": "Community Special School",
        "facilities": ["hydrotherapy", "sensory_room", "physiotherapy", "hearing_support", "wheelchair_access"],
        "age_range": "2-19",
        "region": "West Midlands"
    }
]

FACILITY_LABELS = {
    "sensory_room": "Sensory Room",
    "speech_therapy": "Speech Therapy",
    "aba_unit": "ABA Unit",
    "hydrotherapy": "Hydrotherapy Pool",
    "physiotherapy": "Physiotherapy",
    "occupational_therapy": "Occupational Therapy",
    "counselling": "Counselling Service",
    "hearing_support": "Hearing Support Unit",
    "bsl_unit": "BSL / Sign Language Unit",
    "radio_aid_systems": "Radio Aid Systems",
    "braille_unit": "Braille Unit",
    "low_vision_aids": "Low Vision Aids",
    "orientation_mobility": "Orientation & Mobility Training",
    "wheelchair_access": "Full Wheelchair Access",
    "life_skills_kitchen": "Life Skills Kitchen",
    "vocational_workshop": "Vocational Workshop",
    "art_therapy": "Art Therapy",
    "equine_therapy": "Equine Therapy",
    "outdoor_learning": "Outdoor Learning",
    "sports_therapy": "Sports Therapy",
    "reading_recovery": "Reading Recovery Programme",
    "residential": "Residential Provision",
}

SEN_LABELS = {
    "ASD": "Autism Spectrum Disorder",
    "SEMH": "Social, Emotional & Mental Health",
    "SLCN": "Speech, Language & Communication",
    "MLD": "Moderate Learning Difficulty",
    "SLD": "Severe Learning Difficulty",
    "PMLD": "Profound & Multiple Learning Difficulty",
    "SpLD": "Specific Learning Difficulty",
    "HI": "Hearing Impairment",
    "VI": "Visual Impairment",
    "MSI": "Multi-Sensory Impairment",
    "PD": "Physical Disability",
    "OTH": "Other",
}

OFSTED_ORDER = {"Outstanding": 4, "Good": 3, "Requires Improvement": 2, "Inadequate": 1}
